### ISSUE TITLE
chrome web store not found

### ISSUE THREAD

**Issue by djkloop** [yuichkun/vue-devtool-flash-updates#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome Extension Version [e.g. `v1.0.0`]
 - NPM Package Version [e.g. `v0.1.0`]

**Additional context**

**Comment by yuichkun** [comment]
Sorry, since the official vue plugin [now supports flash updates](https://github.com/vuejs/devtools/commit/d277f40e6271f999410e3a71cb498401ae1d1491), this plugin is now deprecated.

I will archive this repository.
